import React from 'react';

type IconFn = React.FC<React.ImgHTMLAttributes<HTMLImageElement> & { className?: string }>;

const Img = (src: string): IconFn => ({ className, ...props }) => (
  <img src={src} alt="" className={className} {...props} />
);

export const TabletIcon = Img('/icons/tablet.svg');
export const CapsuleIcon = Img('/icons/capsule.svg');
export const BottleIcon = Img('/icons/bottle.svg');
export const InjectionIcon = Img('/icons/injection.svg');
export const InfusionIcon = Img('/icons/infusion.svg');
export const CreamIcon = Img('/icons/cream.svg');
export const OintmentIcon = Img('/icons/ointment.svg');
export const SprayIcon = Img('/icons/spray.svg');
export const DropIcon = Img('/icons/drop.svg');
export const EyeDropperIcon = Img('/icons/eyedropper.svg');
export const PowderIcon = Img('/icons/powder.svg');
export const InhalerIcon = Img('/icons/inhaler.svg');
export const PillIcon = Img('/icons/pill.svg');
export const HerbalIcon = Img('/icons/herbal.svg');
export const SuppositoryIcon = Img('/icons/suppository.svg');

const iconMap: Record<string, IconFn> = {
  tablet: TabletIcon,
  capsule: CapsuleIcon,
  'capsule (enteric coated)': CapsuleIcon,
  'capsule (sustained release)': CapsuleIcon,
  'capsule (extended release)': CapsuleIcon,
  'capsule (modified release)': CapsuleIcon,
  'capsule (delayed release)': CapsuleIcon,
  'capsule (micronized)': CapsuleIcon,
  'soft gel capsule': CapsuleIcon,
  'dr capsule': CapsuleIcon,
  'eye capsule': CapsuleIcon,
  injection: InjectionIcon,
  'im injection': InjectionIcon,
  'iv injection': InjectionIcon,
  'iv infusion': InfusionIcon,
  'iv/im injection': InjectionIcon,
  'im/iv injection': InjectionIcon,
  'sc injection': InjectionIcon,
  'iv/sc injection': InjectionIcon,
  'im/sc injection': InjectionIcon,
  'im/deep sc injection': InjectionIcon,
  'im/ia injection': InjectionIcon,
  'intraspinal injection': InjectionIcon,
  'iv injection or infusion': InfusionIcon,
  'powder for injection': InjectionIcon,
  syrup: BottleIcon,
  'powder for suspension': BottleIcon,
  suspension: BottleIcon,
  'oral suspension': BottleIcon,
  'ophthalmic suspension': DropIcon,
  shampoo: BottleIcon,
  lotion: CreamIcon,
  cream: CreamIcon,
  ointment: OintmentIcon,
  'eye ointment': OintmentIcon,
  'ophthalmic ointment': OintmentIcon,
  'rectal ointment': OintmentIcon,
  'scalp ointment': OintmentIcon,
  'nasal ointment': OintmentIcon,
  gel: CreamIcon,
  'topical gel': CreamIcon,
  'oral gel': CreamIcon,
  'vaginal gel': CreamIcon,
  'eye gel': CreamIcon,
  'ophthalmic gel': CreamIcon,
  drops: DropIcon,
  drop: DropIcon,
  'eye drop': DropIcon,
  'eye drops': DropIcon,
  'eye/ear drop': DropIcon,
  'eye/ear drops': DropIcon,
  'eye/nasal drop': DropIcon,
  'eye/ear/nasal drops': DropIcon,
  'ear drop': DropIcon,
  'ear drops': DropIcon,
  'nasal drop': DropIcon,
  'nasal drops': DropIcon,
  'ophthalmic solution': DropIcon,
  'paediatric drops': DropIcon,
  'pediatric drops': DropIcon,
  'pediatric drop': DropIcon,
  'pediatric nasal drop': DropIcon,
  'nasal spray': SprayIcon,
  spray: SprayIcon,
  'topical spray': SprayIcon,
  bolus: TabletIcon,
  powder: PowderIcon,
  'oral powder': PowderIcon,
  'topical powder': PowderIcon,
  'eff. powder': PowderIcon,
  'effervescent powder': PowderIcon,
  'powder for solution': PowderIcon,
  'oral solution': BottleIcon,
  'concentrated oral solution': BottleIcon,
  solution: BottleIcon,
  'topical solution': BottleIcon,
  'scalp solution': BottleIcon,
  'respirator solution': BottleIcon,
  'nebuliser solution': BottleIcon,
  'solution for inhalation': BottleIcon,
  'irrigation solution': BottleIcon,
  'viscoelastic solution': BottleIcon,
  'dialysis solution': BottleIcon,
  'rectal saline': BottleIcon,
  'saline': BottleIcon,
  'tablet (extended release)': TabletIcon,
  'xr tablet': TabletIcon,
  'tablet (enteric coated)': TabletIcon,
  'tablet (sustained release)': TabletIcon,
  'tablet (controlled release)': TabletIcon,
  'tablet (modified release)': TabletIcon,
  'tablet (delayed release)': TabletIcon,
  'chewable tablet': TabletIcon,
  'dispersible tablet': TabletIcon,
  'mups tablet': TabletIcon,
  'flash tablet': TabletIcon,
  'bilayer tablet': TabletIcon,
  'retard tablet': TabletIcon,
  'effervescent tablet': TabletIcon,
  'sublingual tablet': TabletIcon,
  'buccal tablet': TabletIcon,
  'vaginal tablet': TabletIcon,
  'oros tablet': TabletIcon,
  'orodispersible tablet': TabletIcon,
  'extended-release tablet (wax matrix)': TabletIcon,
  suppository: SuppositoryIcon,
  'vaginal suppository': SuppositoryIcon,
  inhaler: InhalerIcon,
  'inhalation capsule': InhalerIcon,
  'metered-dose inhaler (mdi)': InhalerIcon,
  'mdpi': InhalerIcon,
  'hfa inhaler': InhalerIcon,
  'dry powder inhalation capsule (dpi)': InhalerIcon,
  herbal: HerbalIcon,
  'herbal and others': HerbalIcon,
  infusion: InfusionIcon,
  'emulsion for infusion': InfusionIcon,
  liquid: BottleIcon,
  elixir: BottleIcon,
  emulsion: BottleIcon,
  'oral emulsion': BottleIcon,
  'ophthalmic emulsion': BottleIcon,
  'nebuliser suspension': BottleIcon,
  'suspension for inhalation': BottleIcon,
  'extend release suspension': BottleIcon,
  mouthwash: BottleIcon,
  'oral paste': BottleIcon,
  paste: BottleIcon,
  'oral granules': PowderIcon,
  'eff. granules': PowderIcon,
  'effervescent granules': PowderIcon,
  'microgranules': PowderIcon,
  sachet: PowderIcon,
  'oral soluble film': PowderIcon,
  'vaginal pessary': SuppositoryIcon,
  'topical suspension': BottleIcon,
  'oral drops': DropIcon,
  patch: CreamIcon,
  'transdermal patch': CreamIcon,
  'ear ointment': OintmentIcon,
};

const BlankIcon: IconFn = ({ className }) => <span className={className} style={{ display: 'inline-block', width: '1em', height: '1em' }} />;

export function getDosageIcon(form: string): IconFn {
  const key = (form || '').toLowerCase().trim().replace(/_/g, ' ');
  return iconMap[key] || BlankIcon;
}
